apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgDVL7GFpqwJ6Q1EgAkltwIH9yvYv58kClH/L4ixgjHrEyEF2O29LmOgQs0rdwVbcLRvfxDf/V9PlHfbw50QZiEGJr/SS/klwMepP+Ps4zKYop+7GMFT9vMfGgs12C4QTGh4ju27buPrt7IG/9LxUrgHS8UkI92kZZEllsghrHuyxlPSxLndieimOyTfauMKxtCzLjYy9TwVWB6rpiKBgWSAa12+Ft8jmDfdbSoNoXJvo0eRMnkHynF+gqc7towa6P0n1+XeUyu5oWlNZPI+QruniX39AhmLytUBqJUQn+C9ESqOJNd3TZ1rCJ+i3JMuG0PFCa…YKUDBQhGR7S3IOYoPODtymo3olvF8uDXO/HVrkWMCWaKozV241tMLuOnfBVAbACVDiKaGYq0vZlQXWqJlKUsmxeTij5MER7kZ2GU1xENQvsswJ1T2Qu4A0zZXNBi2/1MJ0ZURaHXHoLWXlackAg5PnzB4M+0KkKCLQA1WYJzEF9bOdcDJ7lah1hHVZP5qxNSq2Mq5imUqVoHf+swmEw7r/vkA95WNsEYojo0tjBg4yGAXI3LcdL3zXk5w8dNW26ibanqYC9+ETAAwmDwekCJWleSQKXrotr0LUttfYuxVvHwfNECtuVSf5qnpb3wIWERDtYQXfUvZaJbEcwmJJef82vCzLbgBqcxyVQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
