apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paypal-cert
  namespace: default
spec:
  encryptedData:
    paypal.crt: AgBSCXgcB4ckXWIuA9G0TDQnLPipIsjj5L7JlqICPzP91mEQVlYckYS0LOGVv3uVfV3kNYlqy2toGmxlYtLZ
gXwfiqLeRt9CdwU30dph/8qnnscpCmZR9F0/Rzapn8tJKJ4BGeHmGjSNaiofmzqYBLAOGlwAw0JBF4GV7krkaQtNmOBZjsNRZcDT
e8IVoqhq5oTgzzoGjyopl8kCSoUnlRfKPcvE+AAHkxL0tFt9IN6Q2mBroUED39RojVpaSHwUWLia8bZjsP0eyBru6IFjRMzPPBFh
9qb/A9EhlneKy/PCx7sjEngeXd4WvSkrELAbG5+p39cr0Wu+b+pfQMQmq4j9uBkA4nMro27jzca3VXM5m9GoNe3mLTyeAj3wsuOj
H4uTwWemJsVqXrE6EC2PBEFKRoM0EfIE78/CIji4dpF8kSKkTZRr/aCWYaXePuYM/yctbqsR9QLTKSPlAvnEVqgMIAleBMgkeryO
Jck0AMdP9qLMcIQwLj2XBqSFY3jmY/9zOat+/7GRLrjwNKGBBica72LN8YwM2Klx3Z+6U8EEbzpu7sy7OMP+DgyS+YaGp3ytfVnM
w8TI99EjWVwS95XcAShzaXpcdHSBdluyQ9F7XKiPNpoBu+Q1gvpEHva/etl3lV2jq0pBCMlVTe/iuRfIuNRun7lwC8lQbHNQXjf+
zWVTKmLOswCqCjgjWwK/g5jZ7Pji/HwKG3bPTdqjWp7r/iEUY/L3LWTCG4eZJIJQ6Lg0LqD14MeZI6VCfcmK7IIPWx3+WHJJdnAO
iTBzeVb4DteFVHFuBv3DjVZKPgcv3uSDmBSzsSjTRYkDb1FrosactLpNj8H71r8XDc0lR2oaTw8i8XeFepH4HXOuPe4vOkpxdQ+I
2k/gm45JYFTIxgqYmxXcLGdCDARQmlRq5kGg/q1DoaZEoFKYzz55HVZkbP4wkKNbDfwHLTpC/pfnrMGwiBg+0xunZUzLx1TFoTxK
P8M3isI9ypaJ0nyzaRthP2/t5fjAxaORaOt7j3yxmwsdI+ybCeCMk+wY9HN7RJ0VMnuo/fX2FbNHsZgdPtO8dSVLum0Les5d/Edh
9jmTphSPqjV4UctyXx7SK3Sal7Enlt4jD7CirVJ4smC63CSm7+9MhaYWXQ0ku+cVYAGfNmghEFqMZq8hROe/3pHXXLx5rCbU4IwB
AU/GQ5aNnrxw69z8nhqbyAYZanb/LHlwFkylNdI+v6gxV1NHH2bjCoFDictFXFPy5jq+BkRkAfFHP6Iyrht4TNUr9wiTULJ6L9IE
rJmKhCSs9zHc0Fw8RQx5NJWDKBnm61z6L82H3vO+Ov32Jobwz/67VPuwHLKrfRNUC8MA8tf9Bz2gA32KUrdQDprlx5ygRGYxzZrA
c6HxlGnnh1fiaM4Cxo6vrwfRsDZs2oQovPq+a73UHSWqm6cvLDyfyFVM3N66fL1DPIgvdtgvOge6WA0NM9WMsjRvaCpL2nsdFZuT
bjIwYPaXaI2eenbzZ8flIDv6jsofpHr8LWPwa9DcZCJGhYsOR7LQVsw7aPpNF8BG1/gkP0fSVCSWI1tLk7XwDup1YLIH/aIa9C5P
kME72kLvUhR7JpJ6W4EUH2WPrWCL6vfkVez0pG2LGyxCR21+TAnwruvJLsQJl/OQdSOp//voY2se6yI3tCp8pR765x5vcXqA/+M3
3SWa9+lLPo8mtVJpL7A3+guIRj12MQFkEJMDwyBvybmPGz2de8jCkfgSk/ICgIlhvvQME3eugoWNQ1Dp1DvgL+zwWYr9No/H/28m
cy4eQFcoo7Vr+SEtMcxVX3Sqmenm3l/EB7ycgQ9zMi1z98lYGcYzwNCIdUwMWsfB1hCRzeGSkGKAac17LsQM69DrpCjEnITbMt2x
sYuPt7FShIQHcGHCRwht/zpOvxbMluTLQCFAnaQbEWk+CpJvLDeJX4CyOysxL6zyTClY+fF2xlqaKfp4EYLxOyfta6hXgiRKOrqU
OjWWP/JeanJ8YwRCW4dXDOZujs9dsq18IvlVzbXVsr11q1OP1OZCcT2t39Ostrr0UDEHyYBdUntsWn8uV6GpnAuAhcV4CH51LKqM
srkFtqbUBxPZ
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: paypal-cert
      namespace: default
    type: Opaque
