apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paypal-cert
  namespace: default
spec:
  encryptedData:
    paypal.crt: AgBWzR3zqaou4iOSIzJxcv8dzhbxPqMX7Mec0SfTUkEQUVLQF0sXimpOuyuiO1ipKOr3G8kJKcHFwOGUIcJ7RG7wTe5OqzutaV+FPcAE+Bfj04G12W2yzn4WTW+5799J+Kgs7DNmVpxdsJxi8N0fyw3qHjdxXKJYUcJxewK33bYBy/duTPVU/yXlc/abG90hm3gE14LLSbnKGtne9ri4L/GkG80oPozkS8k1Pc4WHEQMjOXrXLNoQI17+1xZZq8z5BwOL2mK1c75qIBhakS1nRd3GkMo2ruE6TeRzOK/YYXHB00UXTu5dlyL07Z0kpGv09Zy1tY7ZAb8…D6k+4iD6rqTxjyOzylo8Mm48V964fIQ7/jxx9p2ASOxast3wHkfA4LFjHGWxct4StsN6EHk5Ud3DHgMVAI+sudq2oxskVMhFUx9ggj8JIOYa7O74ZWwps3z0L8R6EeQRqIJVHG5hJDRpUBeWUcySPc3zysJnkiz9wmhk5u2AQ5E+gmne+gSgn+PKhwA3r9IHvyOA06j/quzMxkvasWg1f2ZRxguDoyceVaWn3/7cksb0IICDcH9aNLMRyDj63CNk4/8gvj3qZ757TzbzcqzngH/AJS0fqmjmeKrpbUV8WZrPWVgsARA44QHu5mQi+2xBpVyltZ1MmLTjCfugrJAdR6MHPO5A/mqffEGkn82UhoS
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: paypal-cert
      namespace: default
    type: Opaque
